import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
  {
    key: 'dashboard',
    path: '/dashboard',
    title: 'Panel principal',
    translateKey: 'Panel Principal',
    icon: 'home',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },

  {
    key: 'asignaciones',
    path: '/asignaciones',
    title: 'Asignaciones',
    translateKey: 'Asignaciones',
    icon: 'assingments',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'clientes',
    path: '/clientes',
    title: 'Clientes',
    translateKey: 'Clientes',
    icon: 'clients',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'tickets',
    path: '/tickets',
    title: 'Vuelos',
    translateKey: 'Vuelos',
    icon: 'tickets',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'lodging',
    path: '/hospedajes',
    title: 'Hospedajes',
    translateKey: 'Hospedajes',
    icon: 'lodging',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'insurance',
    path: '/seguros',
    title: 'Seguros',
    translateKey: 'Seguros',
    icon: 'insurance',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'orders',
    path: '/ordenes',
    title: 'Ordenes',
    translateKey: 'Ordenes',
    icon: 'orders',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'emission',
    path: '/emisiones',
    title: 'Emisión',
    translateKey: 'Emisión',
    icon: 'emission',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'usuarios',
    path: '/usuarios',
    title: 'Usuarios',
    translateKey: 'Usuarios',
    icon: 'users',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
]

export default navigationConfig
