export const paymentMethods = [
  { value: 1, label: 'Multipago' },
  { value: 2, label: 'Efectivo USD' },
  { value: 3, label: 'Efectivo COP' },
  { value: 4, label: 'Efectivo ARG' },
  { value: 5, label: 'Efectivo CLP' },
  { value: 6, label: 'Efectivo Euros' },
  { value: 7, label: 'Binance Gracys' },
  { value: 8, label: 'Binance Richard' },
  { value: 9, label: 'Binance Carlos' },
  { value: 10, label: 'Binance Daniel' },
  { value: 11, label: 'Zelle BOFA' },
  { value: 12, label: 'Zelle Wells Fargo' },
  { value: 13, label: 'Davivienda' },
  { value: 14, label: 'Caja Social' },
  { value: 15, label: 'Bancolombia Cta Corriente' },
  { value: 16, label: 'Bancolombia Cta Ahorros' },
  { value: 17, label: 'Banesco Carlos' },
  { value: 18, label: 'Banesco Arcadia' },
  { value: 19, label: 'PDV COP' },
  { value: 20, label: 'PDV ARG' },
  { value: 21, label: 'PDV CLP' },
  { value: 22, label: 'Link de Pago Euros' },
  { value: 23, label: 'Link de Pago Stripe' },
  { value: 24, label: 'Link de Pago MercadoPago' },
  { value: 25, label: 'Mercadopago' },
  { value: 26, label: 'BBVA Frances' },
  { value: 27, label: 'BBVA Victor' },
  { value: 28, label: 'Galicia' },
  { value: 29, label: 'Western Union' },
  { value: 30, label: 'BCP' },
  { value: 31, label: 'Zinli Richard' },
  { value: 32, label: 'Santander Pesos' },
  { value: 33, label: 'Santander USD' },
  { value: 34, label: 'Nickel' },
  { value: 35, label: 'Bizum' },
  { value: 36, label: 'AECorp' },
  { value: 37, label: 'Autorizado Carlos' },
  { value: 38, label: 'Autorizado Richard' },
  { value: 39, label: 'Zelle Chase' },
  { value: 40, label: 'Link de Pago Richard' },
  { value: 41, label: 'Revolut' },
  { value: 42, label: 'Link de Pago Redeban' },
  { value: 43, label: 'BBVA Richard' },
  { value: 44, label: 'Banesco Richard' },
  { value: 45, label: 'Venezuela Richard' },
  { value: 46, label: 'BCP Perú' },
  { value: 47, label: 'Efectivo Soles' },
  { value: 48, label: 'BNC Arcadia' },
]
